name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go Get Modules
      run: go get -uv ./...
    
    - name: Build Server
      run:  go build -o ./server ./terragpio/cmd/server/rpiserver.go 
